### ISSUE TITLE
This file doesn't like on a module

### ISSUE THREAD

**Issue by HeapReaper** [jcarloscid/oauthsso#1]
Hi, if i download the code as a zip, it says a error: This file doesn't look like a module. I tried zip it myself but with no luck

**Comment by jcarloscid** [comment]
Just to be sure where exactly the problem is: Are you using this link?

https://github.com/jcarloscid/oauthsso/releases/download/1.0.1/oauthsso_1.0.1.zip

Using this link I was able to download the module as a Zip file without any issue.

Please copy&paste the exact link you are using or make a screen capture pointing to the element you are using to download the module.

**Comment by jcarloscid** [comment]
I assume your are using this:

![image](https://user-images.githubusercontent.com/35863705/209464035-8632fd51-aeee-4df9-b71d-670afd47d861.png)

This is a convenient way to download the source code of the module, but it is not the fastest if you just want to install it on Prestashop.

Use this link instead: https://github.com/jcarloscid/oauthsso/releases/download/1.0.1/oauthsso_1.0.1.zip

Alternatively you can use the other ZIP file but you need to rename the folder inside the ZIP to be oauthsso (the module name) instead of oauthsso-master (the name given by github).

Lastly you can clone the repo:

`git clone https://github.com/jcarloscid/oauthsso.git`

and then create a ZIP file with the oauthsso folder as the root of the Zip contents.
